In [1]:
import torch

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-14,   5,   4, -23,  98,   3])

In [3]:
tensor = torch.tensor([[0.1, 1.2],[2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
zeros = torch.zeros(2,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
ones = torch.ones(5,6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [6]:
input = torch.empty(3,4)
input

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [9]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [10]:
eye = torch.eye(5)

In [11]:
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
a=torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[5665598740144,             0,             0],
        [            0,             0,             0]])

In [13]:
device= 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [14]:
import numpy as np
import time

In [15]:
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time-start_time
print(f"{elapsed_time:.8f}")

0.00103974


In [17]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time-start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()
elapsed_time = end_time-start_time
print(f"{elapsed_time:.8f}")


0.03203869
0.10994124


In [19]:
%%time

start_time = time.time()
#matric op here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time

print(f"{elapsed_time : 8f}")

 0.000000
CPU times: total: 0 ns
Wall time: 0 ns


In [29]:
#torch.stack, torch.multinomial, torch.tril, torch.triu, inpput.T / input.transpose, nn.linear, torch.cat, F.softmax 
# Define a probability tensor 
probabilities = torch.tensor([0.1, 0.9])

# 0.1 or 10% -> 0.9 or 90% -> 1 or 100% 
#Draw 100 samples from multinomial distribution
samples = torch.multinomial(probabilities, num_samples = 100, replacement=True)
print(samples)

tensor([0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1])


In [28]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [34]:
out = torch.tril(torch.ones(5,5))  #triangle lower
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [35]:
out = torch.triu(torch.ones(5,5))  #triangle upper
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [41]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))== 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [43]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [45]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [50]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

#stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [66]:
import torch.nn as nn
tensor1 = torch.tensor([10.,10.,10.])
linear =nn.Linear(3,3, bias=False)
print(linear(tensor1))

tensor([-8.4773, 11.5341, -0.7857], grad_fn=<SqueezeBackward4>)


In [69]:
import torch.nn.functional as F

tensor1 = torch.tensor([1., 2., 3.])
#apply softmax  using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [73]:
#init the embedding layer

vocab_size = 10000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

# create some input indices
input_indices = torch.LongTensor([1.,5.,3.,2.])

#apply the embedding Layer

embedded_output = embedding(input_indices)

print(embedded_output.shape)
#shape will be a tensor where 4: no. of inputs and 100 = dimension of the embedding vectors


torch.Size([4, 100])


In [75]:
a = torch.tensor([[1,2],[3,4], [5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a@b)  #same as torch.matmul(a,b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [79]:
int_64 = torch.randint(1,(3,2)).float()  # range and ,matrix shape parameters
float_32 = torch.rand(2,3)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [80]:
x= torch.tensor([-0.05], dtype=torch.float32)
y= F.sigmoid(x)
print(y)

tensor([0.4875])


In [82]:
x= torch.tensor([10], dtype=torch.float32)
y= F.tanh(x)
print(y)

tensor([1.])
